### ISSUE TITLE
Dataset mismatch

### ISSUE THREAD

**Issue by hypnopilae** [AIOXLABS/DBert#5]
Hello and thanks for your great work!

The description mentions a 691MB dataset that was used to train this model, but the file in the Data folder is only 8MB.
Can you possibly share the original dataset?

**Comment by KamelGaanoun** [comment]
Hi,
Thanks for your message.
Data used to train the model is not shared yet. The 8MB file is the MTCD dataset.
Please have a look on our preprint paper to have more details.

https://www.researchsquare.com/article/rs-2560653/v1

Best regards.
